services:
  - type: web
    name: sfmc-custom-activity-mensajeria-email
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_BASE_URL
        value: https://sfmc-custom-activity-mensajeria-email.onrender.com
      - key: SFMC_CLIENT_ID
        sync: false
      - key: SFMC_CLIENT_SECRET
        sync: false
      - key: SFMC_AUTH_BASE_URL
        sync: false
      - key: SFMC_REST_BASE_URL
        sync: false
      - key: RELAY_API_URL
        sync: false
      - key: RELAY_API_KEY
        sync: false
      - key: RELAY_TIMEOUT_MS
        value: "15000"